server:
  port: 8040
spring:
  application:
    name: mircroservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbsbk/spring-cloud-study.git
          search-paths: config-repo
          username: mb9177@163.com
          password: LDbgirl17
