server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbsbk/spring-cloud-study.git
          search-paths:  config-repo
          username: mb9177@163.com
          password: LDbgirl17
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/