server:
  port: 0
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

#Feign在新版本中默认是没有开启Hystrix的功能
feign:
  hystrix:
    enabled: true